/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ["class"],
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          border: "hsl(var(--border))",
          foreground: "hsl(var(--foreground))",
          "on-tertiary-fixed": "#002204",
          "surface-container-high": "#e8e8e8",
          "primary-container": "#1b5e20",
          "on-secondary-fixed": "#331200",
          "on-primary-container": "#90d689",
          "secondary-fixed": "#ffdbca",
          "on-primary-fixed": "#002203",
          "error": "#ba1a1a",
          "on-surface": "#1a1c1c",
          "on-surface-variant": "#41493e",
          "outline": "#717a6d",
          "surface-container-low": "#f3f3f3",
          "on-secondary": "#ffffff",
          "tertiary-fixed": "#a3f69c",
          "surface-container-lowest": "#ffffff",
          "surface-bright": "#f9f9f9",
          "background": "#f9f9f9",
          "secondary-container": "#fd7613",
          "on-primary-fixed-variant": "#0c5216",
          "error-container": "#ffdad6",
          "secondary": "#9c4400",
          "inverse-on-surface": "#f1f1f1",
          "surface": "#f9f9f9",
          "surface-container-highest": "#e2e2e2",
          "surface-tint": "#2a6b2c",
          "on-primary": "#ffffff",
          "inverse-surface": "#2f3131",
          "on-tertiary-container": "#86d881",
          "tertiary-fixed-dim": "#88d982",
          "on-secondary-fixed-variant": "#773200",
          "primary": {
            DEFAULT: "#00450d",
            foreground: "#ffffff",
            fixed: "#acf4a4",
            "fixed-dim": "#91d78a"
          },
          "on-secondary-container": "#5b2500",
          "on-tertiary-fixed-variant": "#005312",
          "tertiary-container": "#055f18",
          "on-error": "#ffffff",
          "primary-fixed": "#acf4a4",
          "inverse-primary": "#91d78a",
          "surface-dim": "#dadada",
          "on-tertiary": "#ffffff",
          "on-background": "#1a1c1c",
          "primary-fixed-dim": "#91d78a",
          "secondary-fixed-dim": "#ffb68f",
          "on-error-container": "#93000a",
          "outline-variant": "#c0c9bb",
          "surface-container": "#eeeeee",
          "tertiary": "#00450d",
          "surface-variant": "#e2e2e2"
        },
        fontFamily: {
          headline: ["Cairo", "Plus Jakarta Sans"],
          body: ["Cairo", "Inter"],
          label: ["Cairo", "Inter"],
          cairo: ["Cairo"]
        }
      },
    },
    plugins: [require("tailwindcss-animate")],
  }
