# Generated by Django 4.2.29 on 2026-04-06 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_auditlog_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الموظف')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('working_days_per_month', models.IntegerField(default=26, verbose_name='أيام العمل الشهرية')),
                ('hire_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('on_leave', 'إجازة'), ('terminated', 'منتهي الخدمة')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_date', models.DateField(verbose_name='تاريخ الصرف')),
                ('period', models.CharField(max_length=20, verbose_name='الفترة (مثلاً: 2026-04)')),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم الترحيل المحاسبي؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'تشغيل رواتب',
                'verbose_name_plural': 'تشغيلات الرواتب',
                'unique_together': {('tenant', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_worked', models.IntegerField(verbose_name='أيام العمل الفعلية')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الاستقطاعات')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المكافآت')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='صافي الراتب')),
                ('ledger_posted', models.BooleanField(default=False, verbose_name='تم الترحيل؟')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee', verbose_name='الموظف')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hr.payrollrun')),
            ],
            options={
                'verbose_name': 'بند راتب',
                'verbose_name_plural': 'بنود الرواتب',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'status'], name='hr_employee_tenant__82177c_idx'),
        ),
    ]
