# Generated by Django 4.2.29 on 2026-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='basic_salary',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='bonuses',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='المكافآت'),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='deductions',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='الاستقطاعات'),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='net_salary',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='صافي الراتب'),
        ),
    ]
