# Generated by Django 4.2.29 on 2026-04-06 21:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0004_remove_supplier_commission_rate_commissiontype_and_more'),
        ('core', '0005_alter_auditlog_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_seq', models.PositiveIntegerField(blank=True, verbose_name='رقم تسلسلي يومي')),
                ('tx_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الحركة')),
                ('item_name', models.CharField(max_length=200, verbose_name='الصنف')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوحدة')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='العدد')),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='وزن قائم')),
                ('net_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='وزن صافي')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الشراء')),
                ('purchase_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الشراء')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الكمسيون')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ الكمسيون')),
                ('sale_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='كمية البيع')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر البيع')),
                ('sale_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي البيع')),
                ('box_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ثمن كرتون')),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='رمز العملة')),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قبض نقدي')),
                ('check_received', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قبض شيكات')),
                ('expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='صرف / دفع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='suppliers.customer', verbose_name='المشتري')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='العملة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='suppliers.supplier', verbose_name='المزارع')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'حركة يومية',
                'verbose_name_plural': 'الحركات اليومية',
                'ordering': ['-tx_date', 'daily_seq'],
            },
        ),
    ]
