# Generated by Django 4.2.29 on 2026-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymovement',
            name='box_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='ثمن كرتون'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='cash_received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='قبض نقدي'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='check_received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='قبض شيكات'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='commission_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مبلغ الكمسيون'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='commission_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='نسبة الكمسيون'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='expense_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='صرف / دفع'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='وزن قائم'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='وزن صافي'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='purchase_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='purchase_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='إجمالي الشراء'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='sale_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='sale_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='كمية البيع'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='sale_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='إجمالي البيع'),
        ),
    ]
