# Generated by Django 4.2.29 on 2026-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_dailymovement_box_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymovement',
            name='buyer_commission_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مبلغ عمولة الزبون'),
        ),
        migrations.AddField(
            model_name='dailymovement',
            name='buyer_commission_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='نسبة عمولة الزبون'),
        ),
        migrations.AddField(
            model_name='dailymovement',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رسوم توصيل'),
        ),
        migrations.AddField(
            model_name='dailymovement',
            name='floor_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رسوم أرضية'),
        ),
        migrations.AddField(
            model_name='dailymovement',
            name='loading_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رسوم تحميل'),
        ),
        migrations.AddField(
            model_name='dailymovement',
            name='unloading_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رسوم تنزيل'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='commission_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مبلغ عمولة المزارع'),
        ),
        migrations.AlterField(
            model_name='dailymovement',
            name='commission_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='نسبة عمولة المزارع'),
        ),
    ]
