# Generated by Django 4.2.29 on 2026-04-04 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auditlog_tenantdailysnapshot'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=2)),
                ('account_type', models.CharField(max_length=30)),
                ('account_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.UUIDField()),
                ('description', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'account_type', 'account_id'], name='finance_led_tenant__4993de_idx'), models.Index(fields=['reference_type', 'reference_id'], name='finance_led_referen_8b5bdf_idx')],
            },
        ),
    ]
