# Generated by Django 4.2.29 on 2026-04-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_customer_options_alter_supplier_options_and_more'),
        ('inventory', '0002_alter_category_options_alter_item_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_ledgerentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={'verbose_name': 'حركة خزينة', 'verbose_name_plural': 'حركات الخزينة'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'مصروف', 'verbose_name_plural': 'المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'verbose_name': 'قيد محاسبي', 'verbose_name_plural': 'دفتر الأستاذ (القيود)'},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'verbose_name': 'تصفية إرسالية', 'verbose_name_plural': 'تصفية الإرساليات'},
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='currency_code',
            field=models.CharField(default='ILS', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency_code',
            field=models.CharField(default='ILS', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='currency_code',
            field=models.CharField(default='ILS', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='currency_code',
            field=models.CharField(default='ILS', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='معرف المرجع'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المرجع'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='tx_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='tx_type',
            field=models.CharField(choices=[('in', 'وارد (إيداع)'), ('out', 'منصرف (دفع)')], max_length=5, verbose_name='نوع الحركة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='البيان / الوصف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(verbose_name='تاريخ الصرف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('transport', 'نقل ونولون'), ('loading', 'تنزيل وتحميل'), ('labor', 'عمالة / مشالات'), ('misc', 'أخرى (نثريات)')], max_length=20, verbose_name='نوع المصروف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.shipment', verbose_name='مرتبط بإرسالية'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='account_id',
            field=models.UUIDField(verbose_name='معرف الحساب'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='account_type',
            field=models.CharField(max_length=30, verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='description',
            field=models.CharField(max_length=500, verbose_name='البيان'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ القيد'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('DR', 'مدين (له)'), ('CR', 'دائن (عليه)')], max_length=2, verbose_name='نوع القيد'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reference_id',
            field=models.UUIDField(verbose_name='معرف المرجع'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reference_type',
            field=models.CharField(max_length=50, verbose_name='نوع المرجع'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة العمولة'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تم الدفع؟'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='net_supplier',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الصافي المستحق للمزارع'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التصفية'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.shipment', verbose_name='الإرسالية'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='المزارع'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي المصروفات'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي المبيعات'),
        ),
    ]
