# Generated by Django 4.2.29 on 2026-04-05 22:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_options_alter_customuser_options_and_more'),
        ('finance', '0003_alter_cashtransaction_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='شيك؟'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_number', models.CharField(max_length=50, verbose_name='رقم الشيك')),
                ('bank_name', models.CharField(max_length=100, verbose_name='اسم البنك')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('currency_code', models.CharField(default='ILS', max_length=10, verbose_name='العملة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('cashed', 'تم تحصيله'), ('returned', 'مرتجع'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الشيك')),
                ('drawer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='صاحب الشيك / الساحب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'شيك',
                'verbose_name_plural': 'الشيكات',
            },
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='check_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.check', verbose_name='مرجع الشيك'),
        ),
    ]
