# Generated by Django 4.2.29 on 2026-04-06 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cashtransaction_is_check_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_number', models.CharField(max_length=50, verbose_name='رقم الشيك')),
                ('bank_name', models.CharField(max_length=100, verbose_name='اسم البنك')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفرع')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('currency_code', models.CharField(default='ILS', max_length=10, verbose_name='العملة')),
                ('direction', models.CharField(choices=[('incoming', 'وارد (من الزبون)'), ('outgoing', 'صادر (للمورد)')], default='incoming', max_length=10, verbose_name='اتجاه الشيك')),
                ('lifecycle', models.CharField(choices=[('in_wallet', 'في المحفظة'), ('deposited', 'تم الإيداع'), ('cleared', 'تم التحصيل (مقبول)'), ('bounced', 'مرتجع (شيك ناقص)'), ('cancelled', 'ملغي')], default='in_wallet', max_length=20, verbose_name='حالة الشيك')),
                ('drawer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الساحب')),
                ('deposited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإيداع')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحصيل')),
                ('bounced_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرجوع')),
                ('bounce_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرجوع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شيك (متقدم)',
                'verbose_name_plural': 'الشيكات (متقدم)',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم البنك')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'بنك',
                'verbose_name_plural': 'البنوك',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف مصروف',
                'verbose_name_plural': 'تصنيفات المصاريف',
            },
        ),
        migrations.CreateModel(
            name='RevenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف إيراد',
                'verbose_name_plural': 'تصنيفات الإيرادات',
            },
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
    ]
