# Generated by Django 4.2.29 on 2026-04-06 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_remove_supplier_commission_rate_commissiontype_and_more'),
        ('core', '0005_alter_auditlog_options_alter_customuser_options_and_more'),
        ('finance', '0005_advancedcheck_bank_expensecategory_revenuecategory_and_more'),
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='daily_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='market.dailymovement', verbose_name='مرتبط بحركة ساحة'),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='bank',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='advancedcheck',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
        migrations.AddField(
            model_name='advancedcheck',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.customer', verbose_name='الزبون (شيك وارد)'),
        ),
        migrations.AddField(
            model_name='advancedcheck',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='المورد (شيك صادر)'),
        ),
        migrations.AddField(
            model_name='advancedcheck',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.expensecategory', verbose_name='تصنيف المصروف'),
        ),
        migrations.AddIndex(
            model_name='advancedcheck',
            index=models.Index(fields=['tenant', 'lifecycle'], name='finance_adv_tenant__fb0f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedcheck',
            index=models.Index(fields=['tenant', 'due_date'], name='finance_adv_tenant__8c51ed_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedcheck',
            index=models.Index(fields=['tenant', 'direction'], name='finance_adv_tenant__326c29_idx'),
        ),
    ]
