# Generated by Django 4.2.29 on 2026-04-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_check_daily_movement_revenuecategory_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السند'),
        ),
    ]
