# Generated by Django 4.2.29 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_cashtransaction_voucher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='سعر الصرف'),
        ),
    ]
