# Generated by Django 4.2.29 on 2026-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_cashtransaction_exchange_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='voucher_number',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='amount',
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='base_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='المبلغ (العملة الأساسية)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='foreign_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='المبلغ (عملة الحركة)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='base_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='المبلغ (العملة الأساسية)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='سعر الصرف'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='foreign_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='المبلغ (عملة الحركة)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advancedcheck',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='check',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='commission_amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='قيمة العمولة'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='net_supplier',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الصافي المستحق للمزارع'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='total_expenses',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='إجمالي المصروفات'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='total_sales',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='إجمالي المبيعات'),
        ),
    ]
