# Generated by Django 4.2.29 on 2026-04-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_cashtransaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.AddField(
            model_name='expense',
            name='base_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='المبلغ (عملة الأساس / شيكل)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='سعر الصرف'),
        ),
        migrations.AddField(
            model_name='expense',
            name='foreign_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='المبلغ (عملة الحركة)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='foreign_amount',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='المبلغ (عملة الحركة)'),
        ),
    ]
