# Generated by Django 4.2.29 on 2026-04-09 21:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_bank_alter_tenantdailysnapshot_cash_sales_and_more'),
        ('finance', '0010_expense_4field_brd_cashtx_maxdigits18'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='اسم المجموعة')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='كود المجموعة')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20, verbose_name='نوع الحساب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='finance.accountgroup', verbose_name='المجموعة الأب')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'مجموعة حسابات',
                'verbose_name_plural': 'مجموعات الحسابات',
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='اسم الحساب')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.accountgroup', verbose_name='المجموعة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'حساب مالي',
                'verbose_name_plural': 'شجرة الحسابات',
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
