# Generated by Django 4.2.29 on 2026-04-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_chart_of_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedcheck',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='check',
            name='amount',
        ),
        migrations.AddField(
            model_name='advancedcheck',
            name='base_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='المبلغ (العملة الأساسية)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advancedcheck',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='سعر الصرف'),
        ),
        migrations.AddField(
            model_name='advancedcheck',
            name='foreign_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='المبلغ (عملة الحركة)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='check',
            name='base_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='المبلغ (العملة الأساسية)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='check',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='سعر الصرف'),
        ),
        migrations.AddField(
            model_name='check',
            name='foreign_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='المبلغ (عملة الحركة)'),
            preserve_default=False,
        ),
    ]
