# Generated by Django 4.2.29 on 2026-04-11 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auditlog_after_data_alter_auditlog_before_data_and_more'),
        ('finance', '0012_checks_4field_brd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='اسم الشريك')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('share_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الشراكة (%)')),
                ('initial_capital', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='رأس المال المبدئي')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء والمساهمون',
            },
        ),
    ]
