# Generated by Django 4.2.29 on 2026-04-12 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auditlog_after_data_alter_auditlog_before_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0013_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_date', models.DateField(auto_now_add=True, verbose_name='تاريخ المستند')),
                ('currency_code', models.CharField(default='ILS', max_length=10, verbose_name='العملة')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='سعر الصرف')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='المبلغ')),
                ('base_amount', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='المبلغ (بالأساس)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='البيان')),
                ('dr_account_type', models.CharField(max_length=50, verbose_name='نوع حساب المدين')),
                ('dr_account_id', models.UUIDField(verbose_name='معرف حساب المدين')),
                ('dr_account_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم حساب المدين')),
                ('cr_account_type', models.CharField(max_length=50, verbose_name='نوع حساب الدائن')),
                ('cr_account_id', models.UUIDField(verbose_name='معرف حساب الدائن')),
                ('cr_account_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم حساب الدائن')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'مستند قيد',
                'verbose_name_plural': 'مستندات القيد',
            },
        ),
    ]
