# Generated by Django 4.2.29 on 2026-04-05 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_customer_options_alter_supplier_options_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'التصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'الصنف', 'verbose_name_plural': 'الأصناف'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'الإرسالية', 'verbose_name_plural': 'الإرساليات'},
        ),
        migrations.AlterModelOptions(
            name='shipmentitem',
            options={'verbose_name': 'بند إرسالية', 'verbose_name_plural': 'بنود الإرسالية'},
        ),
        migrations.AlterModelOptions(
            name='unitconversion',
            options={'verbose_name': 'معامل تحويل', 'verbose_name_plural': 'معاملات التحويل'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='base_unit',
            field=models.CharField(choices=[('kg', 'كيلوجرام'), ('box', 'صندوق / قفص'), ('sack', 'شوال'), ('bunch', 'ربطة')], default='kg', max_length=10, verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الصنف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='waste_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة الهالك (%)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='deal_type',
            field=models.CharField(choices=[('commission', 'كمسيون (حِسبة)'), ('direct_purchase', 'شراء مباشر')], default='commission', max_length=20, verbose_name='نظام التعامل'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(verbose_name='تاريخ الإرسالية'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة (قيد البيع)'), ('settled', 'تمت التصفية')], default='open', max_length=20, verbose_name='حالة الإرسالية'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='المزارع'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='boxes_count',
            field=models.IntegerField(default=0, verbose_name='عدد الفوارغ (العبوات)'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='expected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر المتوقع'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية الواردة'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='remaining_qty',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية المتبقية'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.shipment', verbose_name='الإرسالية'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='factor',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='معامل التحويل'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='from_unit',
            field=models.CharField(max_length=20, verbose_name='من وحدة'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='to_unit',
            field=models.CharField(max_length=20, verbose_name='إلى وحدة'),
        ),
    ]
