# Generated by Django 4.2.29 on 2026-04-06 21:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_options_alter_customuser_options_and_more'),
        ('inventory', '0002_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='box_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ثمن الكرتون (افتراضي)'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='cost_center',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='driver_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم السائق'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='عتالة'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='plastic_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة البلاستيك'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة النقل'),
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=50, verbose_name='اسم الوحدة')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='معامل التحويل من الوحدة الأساسية')),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الشراء')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع')),
                ('is_default', models.BooleanField(default=False, verbose_name='وحدة افتراضية؟')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.item', verbose_name='الصنف')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'وحدة صنف',
                'verbose_name_plural': 'وحدات الأصناف',
                'indexes': [models.Index(fields=['tenant', 'item'], name='inventory_i_tenant__d212be_idx')],
                'unique_together': {('tenant', 'item', 'unit_name')},
            },
        ),
    ]
