# Generated by Django 4.2.29 on 2026-04-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_box_price_shipmentitem_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_on',
            field=models.CharField(choices=[('gross', 'القائم (إجمالي)'), ('net', 'الصافي')], default='net', max_length=10, verbose_name='احتساب السعر على'),
        ),
        migrations.AddField(
            model_name='item',
            name='tare_unit',
            field=models.CharField(default='kg', max_length=10, verbose_name='وحدة التارة'),
        ),
        migrations.AddField(
            model_name='item',
            name='tare_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='وزن الفارغ / التارة (كجم لكل وحدة)'),
        ),
    ]
