# Generated by Django 4.2.29 on 2026-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_price_on_item_tare_unit_item_tare_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_on',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tare_unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tare_weight',
        ),
        migrations.AlterField(
            model_name='item',
            name='box_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='ثمن الكرتون (افتراضي)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='waste_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='نسبة الهالك (%)'),
        ),
        migrations.AlterField(
            model_name='itemunit',
            name='buy_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='itemunit',
            name='sell_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='expected_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='السعر المتوقع'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='labor_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='عتالة'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='plastic_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='تكلفة البلاستيك'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='transport_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='تكلفة النقل'),
        ),
    ]
