# Generated by Django 4.2.29 on 2026-04-10 19:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_bank_alter_tenantdailysnapshot_cash_sales_and_more'),
        ('inventory', '0006_item_price_on_item_tare_unit_item_tare_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوحدة')),
                ('has_empties', models.BooleanField(default=False, verbose_name='يوجد بها فوارغ (تُسترجع)؟')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'الوحدة',
                'verbose_name_plural': 'الوحدات المحددة',
            },
        ),
    ]
