# Generated by Django 4.2.29 on 2026-04-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_globalunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='base_unit',
            field=models.CharField(default='kg', max_length=50, verbose_name='وحدة القياس'),
        ),
    ]
