# Generated by Django 4.2.29 on 2026-04-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_customer_options_alter_supplier_options_and_more'),
        ('inventory', '0002_alter_category_options_alter_item_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_add_sale_cancellation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containertransaction',
            options={'verbose_name': 'حركة فوارغ', 'verbose_name_plural': 'حركات الفوارغ'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'فاتورة بيع', 'verbose_name_plural': 'فواتير البيع'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'بند فاتورة', 'verbose_name_plural': 'بنود الفاتورة'},
        ),
        migrations.AddField(
            model_name='sale',
            name='currency_code',
            field=models.CharField(default='ILS', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='containertransaction',
            name='container_type',
            field=models.CharField(max_length=100, verbose_name='نوع الفارغ'),
        ),
        migrations.AlterField(
            model_name='containertransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.customer', verbose_name='الزبون / تاجر'),
        ),
        migrations.AlterField(
            model_name='containertransaction',
            name='direction',
            field=models.CharField(choices=[('out', 'صرف (إلى الزبون)'), ('return', 'استلام (مُرتجع من الزبون)')], max_length=10, verbose_name='اتجاه الحركة'),
        ),
        migrations.AlterField(
            model_name='containertransaction',
            name='quantity',
            field=models.IntegerField(verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='containertransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale', verbose_name='مرتبط بفاتورة'),
        ),
        migrations.AlterField(
            model_name='containertransaction',
            name='tx_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='سبب الإلغاء'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sales', to=settings.AUTH_USER_MODEL, verbose_name='ملغاة بواسطة'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.customer', verbose_name='الزبون / تاجر'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ملغاة؟'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل (ذمة)')], default='cash', max_length=10, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البيع'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الفاتورة'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='containers_out',
            field=models.IntegerField(default=0, verbose_name='الفوارغ الصادرة'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية المباعة'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='shipment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.shipmentitem', verbose_name='بند الإرسالية'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي الفرعي'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة'),
        ),
    ]
