# Generated by Django 4.2.29 on 2026-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_purchaseorder_purchasereturn_salereturn_salesorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم الفاتورة'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='العمولة المتفق عليها لهذا البند', max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن القائم'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن الصافي'),
        ),
    ]
