# Generated by Django 4.2.29 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_discount_saleitem_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='سعر الصرف'),
        ),
    ]
