# Generated by Django 4.2.29 on 2026-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_exchange_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='net_weight',
        ),
        migrations.AddField(
            model_name='sale',
            name='base_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='إجمالي الفاتورة (أساسي)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='foreign_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='إجمالي الفاتورة (أجنبي)'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الإجمالي الفرعي'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='قيمة المرتجع'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الإجمالي الفرعي'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='return_amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='قيمة المرتجع'),
        ),
        migrations.AlterField(
            model_name='salereturnitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='salereturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الإجمالي الفرعي'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='السعر'),
        ),
    ]
