# Generated by Django 4.2.29 on 2026-04-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_sale_discount_remove_sale_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة العمولة (%)'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='خصم الصنف'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن القائم'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن الصافي'),
        ),
    ]
