# Generated by Django 4.2.29 on 2026-04-10 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saleitem_commission_rate_saleitem_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ البيع'),
        ),
    ]
