# Generated by Django 4.2.29 on 2026-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='ط±ط³ظˆظ… طھظˆطµظٹظ„'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='floor_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='ط±ط³ظˆظ… ط£ط±ط¶ظٹط©'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='loading_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='ط±ط³ظˆظ… طھط­ظ…ظٹظ„'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unloading_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='ط±ط³ظˆظ… طھظ†ط²ظٹظ„'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='ط¹ظ…ظˆظ„ط© ط§ظ„ظ…ط²ط§ط±ط¹ (%)'),
        ),
    ]
