# Generated by Django 4.2.29 on 2026-04-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_saleitem_delivery_fee_saleitem_floor_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='buyer_commission_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='عمولة المشتري (%)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='عمولة المزارع (%)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='رسوم توصيل'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='floor_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='رسوم أرضية'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='loading_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='رسوم تحميل'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unloading_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='رسوم تنزيل'),
        ),
    ]
