# Generated by Django 4.2.29 on 2026-04-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'الزبون / تاجر', 'verbose_name_plural': 'الزبائن / تجار'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'المزارع', 'verbose_name_plural': 'المزارعين'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد المديونية'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='حد الائتمان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('trader', 'تاجر / زبون دائم'), ('retail', 'قطاعي / تجزئة'), ('individual', 'فردي')], default='trader', max_length=20, verbose_name='تصنيف الزبون'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الزبون / تاجر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='رصيد الحساب'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='نسبة/قيمة العمولة'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='commission_type',
            field=models.CharField(choices=[('percent', 'نسبة مئوية (%)'), ('fixed', 'مبلغ ثابت (ج)')], default='percent', max_length=20, verbose_name='نوع العمولة'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='deal_type',
            field=models.CharField(choices=[('commission', 'كمسيون (حِسبة)'), ('direct_purchase', 'شراء مباشر')], default='commission', max_length=20, verbose_name='نوع التعامل'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المزارع'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم واتساب'),
        ),
    ]
