# Generated by Django 4.2.29 on 2026-04-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_remove_supplier_commission_rate_commissiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة الكميسيون (%)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم واتساب'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة الكميسيون (%)'),
        ),
    ]
