# Generated by Django 4.2.29 on 2026-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_customer_commission_rate_customer_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontype',
            name='calc_basis',
            field=models.CharField(choices=[('NET_WEIGHT', 'تُحسب على الوزن الصافي'), ('GROSS_WEIGHT', 'تُحسب على الوزن القائم'), ('QUANTITY', 'تُحسب القطعة/العدد'), ('AMOUNT', 'تُحسب على إجمالي المبلغ')], default='AMOUNT', max_length=20, verbose_name='أساس الاحتساب (الكمية أو المبلغ)'),
        ),
    ]
