# Generated by Django 4.2.29 on 2026-04-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_commissiontype_calc_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='commission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.commissiontype', verbose_name='نوع العمولة المرتبط'),
        ),
    ]
