# Generated by Django 4.2.29 on 2026-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_customer_commission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissiontype',
            name='calc_basis',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='commission_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='commission_rate',
        ),
        migrations.AlterField(
            model_name='commissiontype',
            name='default_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='نسبة/قيمة العمولة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='رصيد المديونية'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='حد الائتمان'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='رصيد الحساب'),
        ),
    ]
