# Generated by Django 4.2.29 on 2026-04-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_remove_commissiontype_calc_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='commission_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='نسبة عمولة الزبون (%) — جزئي إذا لم يُحدد نوع'),
        ),
        migrations.AddField(
            model_name='customer',
            name='commission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='suppliers.commissiontype', verbose_name='نوع عمولة الزبون (تُضاف للفاتورة)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم واتساب'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('trader', 'تاجر / زبون دائم'), ('retail', 'قطاعي / تجزئة'), ('individual', 'فردي'), ('employee', 'موظف'), ('partner', 'شريك')], default='trader', max_length=20, verbose_name='تصنيف الزبون'),
        ),
    ]
