# Generated by Django 4.2.29 on 2026-04-03 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('delta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantDailySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('sales_count', models.IntegerField(default=0)),
                ('sales_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('settlements_count', models.IntegerField(default=0)),
                ('commissions_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('active_users', models.IntegerField(default=0)),
                ('login_count', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'date')},
            },
        ),
    ]
