# Generated by Django 4.2.29 on 2026-04-05 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'سجل الرقابة', 'verbose_name_plural': 'سجلات الرقابة والعمليات'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'المستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'المحل / الوكالة', 'verbose_name_plural': 'المحلات والوكالات المشتركة'},
        ),
        migrations.AlterModelOptions(
            name='tenantdailysnapshot',
            options={'verbose_name': 'ملخص الأداء اليومي', 'verbose_name_plural': 'ملخصات الأداء اليومية'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='base_currency_code',
            field=models.CharField(default='ILS', max_length=10, verbose_name='كود العملة الأساسية'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='base_currency_symbol',
            field=models.CharField(default='₪', max_length=5, verbose_name='رمز العملة الأساسية'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='after_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='البيانات الجديدة'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='before_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='البيانات السابقة'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='delta',
            field=models.JSONField(blank=True, default=dict, verbose_name='الفروقات'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف الكيان'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(max_length=100, verbose_name='نوع الكيان'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant', verbose_name='المحل'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'إدارة النظام'), ('owner', 'صاحب المحل'), ('cashier', 'كاشير')], default='cashier', max_length=20, verbose_name='الصلاحية'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant', verbose_name='المحل التابع له'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم المحل / الوكالة'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('trial', 'تجريبي'), ('expired', 'منتهي'), ('suspended', 'موقوف')], default='trial', max_length=20, verbose_name='حالة الاشتراك'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رابط الموقع (Subdomain)'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الفترة التجريبية'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='active_users',
            field=models.IntegerField(default=0, verbose_name='المستخدمين النشطين'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='cash_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبيعات النقدية'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='commissions_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي العمولات'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='credit_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='المبيعات الآجلة'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='error_count',
            field=models.IntegerField(default=0, verbose_name='عدد الأخطاء'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر نشاط'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='login_count',
            field=models.IntegerField(default=0, verbose_name='عدد مرات الدخول'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='sales_count',
            field=models.IntegerField(default=0, verbose_name='عدد المبيعات'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='sales_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي المبيعات'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='settlements_count',
            field=models.IntegerField(default=0, verbose_name='عدد التصفيات'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='core.tenant', verbose_name='المحل'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='warning_count',
            field=models.IntegerField(default=0, verbose_name='عدد التحذيرات'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, verbose_name='كود العملة (مثل ILS)')),
                ('name', models.CharField(max_length=50, verbose_name='اسم العملة')),
                ('symbol', models.CharField(max_length=5, verbose_name='الرمز')),
                ('is_base', models.BooleanField(default=False, verbose_name='العملة الأساسية؟')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_currencies', to='core.tenant')),
            ],
            options={
                'verbose_name': 'العملة',
                'verbose_name_plural': 'العملات',
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
