# Generated by Django 4.2.29 on 2026-04-07 19:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود البنك')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم البنك (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='اسم البنك (إنجليزي)')),
                ('swift_code', models.CharField(blank=True, max_length=20, verbose_name='SWIFT Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'بنك',
                'verbose_name_plural': 'البنوك',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('SALE_INVOICE', 'فاتورة مبيعات'), ('PURCHASE_INVOICE', 'فاتورة مشتريات'), ('SALE_RETURN', 'مرتجع مبيعات'), ('PURCHASE_RETURN', 'مرتجع مشتريات'), ('RECEIPT', 'سند قبض'), ('PAYMENT', 'سند صرف'), ('JOURNAL', 'قيد يومي')], max_length=30, verbose_name='نوع المستند')),
                ('prefix', models.CharField(max_length=10, verbose_name='البادئة')),
                ('last_number', models.IntegerField(default=0, verbose_name='آخر رقم')),
                ('fiscal_year', models.IntegerField(verbose_name='السنة المالية')),
                ('reset_yearly', models.BooleanField(default=True, verbose_name='يُعاد احتساب سنوياً')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='core.tenant', verbose_name='المحل')),
            ],
            options={
                'verbose_name': 'تسلسل مستند',
                'verbose_name_plural': 'تسلسلات المستندات',
                'unique_together': {('tenant', 'doc_type', 'fiscal_year')},
            },
        ),
    ]
