# Generated by Django 4.2.29 on 2026-04-09 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bank_documentsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='سعر الصرف')),
                ('date', models.DateField(verbose_name='تاريخ التسعيرة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.currency')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.tenant')),
            ],
            options={
                'verbose_name': 'سعر صرف',
                'verbose_name_plural': 'أسعار الصرف',
                'unique_together': {('tenant', 'currency', 'date')},
            },
        ),
    ]
