# Generated by Django 4.2.29 on 2026-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_currencyexchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='cash_sales',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='المبيعات النقدية'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='commissions_earned',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='إجمالي العمولات'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='credit_sales',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='المبيعات الآجلة'),
        ),
        migrations.AlterField(
            model_name='tenantdailysnapshot',
            name='sales_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='إجمالي المبيعات'),
        ),
        migrations.DeleteModel(
            name='DocumentSequence',
        ),
    ]
