# Generated by Django 4.2.29 on 2026-04-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_bank_alter_tenantdailysnapshot_cash_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='الصلاحيات التفصيلية'),
        ),
    ]
