# Generated by Django 4.2.29 on 2026-04-11 13:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='after_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='البيانات الجديدة'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='before_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='البيانات السابقة'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='delta',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='الفروقات'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='الصلاحيات التفصيلية'),
        ),
    ]
